"""
daily_summary.py — End-of-day site activity summary via email

Pulls today's entries from Google Sheets, asks Gemini to summarise,
and emails the result to the site manager.

Run manually:  python daily_summary.py
Schedule via cron (runs at 6 PM every day):
  0 18 * * * cd /path/to/voice_site_reporter && python daily_summary.py
"""

import os
import smtplib
import ssl
from datetime import datetime, date
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import google.generativeai as genai

from sheets_logger import get_all_as_dicts

load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

MANAGER_EMAIL   = os.getenv("MANAGER_EMAIL")
SENDER_EMAIL    = os.getenv("SENDER_EMAIL")     # Gmail address you send from
SENDER_PASSWORD = os.getenv("SENDER_APP_PASSWORD")  # Gmail App Password (not your real password)


# ── Pull today's rows from Sheets ──────────────────────────────
def get_todays_entries() -> list[dict]:
    all_rows = get_all_as_dicts()
    today_str = date.today().strftime("%Y-%m-%d")
    return [r for r in all_rows if str(r.get("Timestamp", "")).startswith(today_str)]


# ── Build summary with Gemini ───────────────────────────────────
def generate_summary(entries: list[dict]) -> str:
    if not entries:
        return "No site activity was recorded today."

    # Format entries as a readable table for Gemini
    lines = []
    for e in entries:
        line = (
            f"- [{e.get('Timestamp','')}] "
            f"Site: {e.get('Site Name','?')} | "
            f"Machine: {e.get('Machine ID','?')} | "
            f"Activity: {e.get('Activity','?')} | "
            f"Material: {e.get('Material','?')} | "
            f"Qty: {e.get('Quantity','?')} {e.get('Unit','')} | "
            f"By: {e.get('Reported By','?')}"
        )
        if e.get("Anomaly Flag"):
            line += f" | ⚠️ {e['Anomaly Flag']}"
        lines.append(line)

    entries_text = "\n".join(lines)

    prompt = f"""
You are a site manager's assistant for an Indian earthmoving/construction company.
Summarise today's site activity log in clear, professional English.

Today's entries:
{entries_text}

Write a concise daily summary report that includes:
1. Total number of entries logged today
2. Sites that were active
3. Key activities (diesel filling, deliveries, etc.) with totals where possible
4. Any anomalies or flags that need attention
5. A one-line overall assessment of the day

Keep it brief — 150 words max. Use bullet points.
Start with: "Daily Site Report — {date.today().strftime('%d %B %Y')}"
"""

    from pipeline import _get_working_model_name
    model = genai.GenerativeModel(_get_working_model_name())
    response = model.generate_content(prompt)
    return response.text.strip()


# ── Send email ──────────────────────────────────────────────────
def send_summary_email(summary: str, entry_count: int):
    if not all([MANAGER_EMAIL, SENDER_EMAIL, SENDER_PASSWORD]):
        print("⚠️  Email not configured. Add MANAGER_EMAIL, SENDER_EMAIL, SENDER_APP_PASSWORD to .env")
        print("\n--- Summary (would have been emailed) ---")
        print(summary)
        return

    today = date.today().strftime("%d %B %Y")
    subject = f"📋 Daily Site Report — {today} ({entry_count} entries)"

    # Plain text version
    plain = summary

    # HTML version
    html_summary = summary.replace("\n", "<br>")
    html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 600px; margin: auto;">
        <div style="background:#2C3E50; color:white; padding:16px 20px; border-radius:8px 8px 0 0;">
            <h2 style="margin:0">🏗️ Daily Site Report</h2>
            <p style="margin:4px 0 0; opacity:0.8">{today}</p>
        </div>
        <div style="background:#f8f9fa; padding:20px; border-radius:0 0 8px 8px;">
            <p>{html_summary}</p>
            <hr style="border:none; border-top:1px solid #dee2e6; margin:16px 0">
            <p style="color:#6c757d; font-size:12px">
                Generated by Voice Site Reporter • {entry_count} entries logged today<br>
                View full data: <a href="https://sheets.google.com">Google Sheets</a>
            </p>
        </div>
    </body></html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = SENDER_EMAIL
    msg["To"]      = MANAGER_EMAIL
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, MANAGER_EMAIL, msg.as_string())

    print(f"✅ Summary emailed to {MANAGER_EMAIL}")


# ── Main ────────────────────────────────────────────────────────
if __name__ == "__main__":
    print(f"📋 Generating daily summary for {date.today()}...")

    entries = get_todays_entries()
    print(f"   Found {len(entries)} entries today")

    summary = generate_summary(entries)
    print("\n--- Summary ---")
    print(summary)
    print("---------------\n")

    send_summary_email(summary, len(entries))
